### ISSUE TITLE
Bug 1

### ISSUE THREAD

**Issue by NoahLandon** [NoahLandon/IT480---Homework-2-Max-Noah-Steven#1]
Hi Willie. There is a new bug within the code that needs to be fixed and I believe it requires some attention in the near future.

**Comment by Maxnagel** [comment]
Jill, I cannot fix this bug. Please find a new member to take it over.

**Comment by NoahLandon** [comment]
Sorry Willie, but I believe this bug really needs to be fixed in the near future. :)

**Comment by Maxnagel** [comment]
Mikey, I'm going to need you to take over for me on this bug, as I cannot fix it.

**Comment by ghost** [comment]
Okay I fixed the bug! :)

**Comment by NoahLandon** [comment]
I'm sorry Mikey, but it doesn't seem like the bug was fixed..... Please take another look.

**Comment by ghost** [comment]
I fixed it for real this time. Sorry I was in a meeting.

**Comment by NoahLandon** [comment]
Looks good Mikey. Thanks for the help :)
